CREATE TABLE users
(
	id			INT				PRIMARY KEY AUTO_INCREMENT
	,login_id	VARCHAR(20)		UNIQUE NOT NULL
	,passward	VARCHAR(255)	NOT NULL
	,name		VARCHAR(10)		NOT NULL
	,branch_id		INT			NOT NULL
	,department_id	INT			NOT NULL
	,is_stopped		BIT(1)		NOT NULL
	,timed_at	TIMESTAMP		NOT NULL
	,updated_at	TIMESTAMP		NOT NULL
);

CREATE TABLE branches
(
	id			INT				PRIMARY KEY AUTO_INCREMENT
	,name		VARCHAR(255)	NOT NULL
	,timed_at	TIMESTAMP		NOT NULL
	,updated_at	TIMESTAMP		NOT NULL
);

CREATE TABLE departments
(
	id			INT				PRIMARY KEY AUTO_INCREMENT
	,name		VARCHAR(255)	NOT NULL
	,timed_at	TIMESTAMP		NOT NULL
	,updated_at	TIMESTAMP		NOT NULL
);

CREATE TABLE posts
(
	id			INT				PRIMARY KEY AUTO_INCREMENT
	,title		VARCHAR(50)		NOT NULL
	,text		VARCHAR(1000)	NOT NULL
	,category	VARCHAR(10)		NOT NULL
	,timed_at	TIMESTAMP		NOT NULL
	,updated_at	TIMESTAMP		NOT NULL
	,user_id	INT				NOT NULL
);

CREATE TABLE comments
(
	id			INT				PRIMARY KEY AUTO_INCREMENT
	,text		VARCHAR(500)	NOT NULL
	,timed_at	TIMESTAMP		NOT NULL
	,updated_at	TIMESTAMP		NOT NULL
	,post_id	INT				NOT NULL 
	,user_id	INT				NOT NULL
);

CREATE TABLE categories
(
	id	INT	PRIMARY KEY AUTO_INCREMENT
    ,category	VARCHAR(10)	UNIQUE NOT NULL
    ,timed_at	TIMESTAMP	NOT NULL
    ,updated_at	TIMESTAMP	NOT NULL
);
